### ISSUE TITLE
Benchmark instances

### ISSUE THREAD

**Issue by leonlan** [rsobralm/SMRDSDST#1]
Hi @rsobralm,

Congrats on your publication in EJOR! I went through the paper and it's a nice piece of work. 

For my own scheduling projects, I'm interested in the 1800 instances that you use from [1]. I read [1] but it seems that the instance generation procedure is random, so it'd almost impossible to generate the same instances. Do you have the instances available, and if so, would you be willing to share them with me? Thanks a lot in advance.

- [1] Ovacikt IM, Uzsoy R. Rolling horizon algorithms for a single-machine dynamic scheduling problem with sequence-dependent setup times. Int. J. Prod. Res. 1994;32(6):1243–63.

**Comment by rsobralm** [comment]
Hi @leonlan, thank you for your interest in our research. I've updated the repository to include the instances along with a file explaining how to read them.

**Comment by leonlan** [comment]
Thanks a lot @rsobralm!
